SELECT 
PFUNC.CHAPA, 
PFUNC.NOME, 
PFUNC.CODFUNCAO, 
PFUNCAO.NOME FUNCAO,
PFUNC.CODSITUACAO

FROM PFUNC
LEFT JOIN PFUNCAO (NOLOCK) ON PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFUNCAO.CODIGO = PFUNC.CODFUNCAO 
WHERE
PFUNC.CODSITUACAO <> 'D'
AND PFUNC.NOME LIKE CONCAT(UPPER(:CHNO), '%')
ORDER BY PFUNC.NOME ASC