SELECT 
PFUNC.CHAPA, 
PFUNC.NOME, 
PFUNC.CODFUNCAO, 
PFUNCAO.NOME FUNCAO,
PFUNC.CODSITUACAO,
PFUNC.CODSECAO,
PSECAO.DESCRICAO AS SECAO,
PFUNC.CODEQUIPE AS CODIGO_LIDER,
PEQUIPE.DESCRICAO NOME_LIDER,
PFUNC.DATADEMISSAO DATADEMISSAO, 
PFUNC.DATAADMISSAO DATAADMISSAO

FROM PFUNC
LEFT JOIN PFUNCAO (NOLOCK) ON PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFUNCAO.CODIGO = PFUNC.CODFUNCAO 
LEFT JOIN PSECAO  (NOLOCK) ON PSECAO.CODCOLIGADA  = PFUNC.CODCOLIGADA AND PSECAO.CODIGO  = PFUNC.CODSECAO
FULL JOIN PEQUIPE (NOLOCK) ON PEQUIPE.CODCLIENTE  = PFUNC.CODEQUIPE 

WHERE
PFUNC.NOME LIKE CONCAT(UPPER(:NOME), '%')

ORDER BY PFUNC.NOME ASC