var myQuery = "CREATE TABLE GESTAO_CTQF( " +
			"NOME_USUARIO VARCHAR(255) NOT NULL, " + 
			"MATRICULA VARCHAR(255) NOT NULL, " +
			"CPF VARCHAR(255) NOT NULL, " +
			"RG VARCHAR(255) NOT NULL, " +
			"CARGO VARCHAR(255) NOT NULL " +
			")";


var myQuery = "INSERT INTO GESTAO_CTQF " +
	"(NOME_USUARIO, MATRICULA, CPF, RG, CARGO) " +
	"VALUES ('TESTE', '999999', '99999999999', '99999999', 'CARGO TESTE')";
			
var myQuery = "SELECT * FROM GESTAO_CTQF ";

var myQuery = "TRUNCATE TABLE GESTAO_CTQF "; 
			