// Itens do Contratos
SELECT 
MITMCNT.IDPRJ AS IDPRJ,
MITMCNT.IDCNT AS IDCNT,
MPDO.PERIODOMED AS PERIODOMED,
MPRJ.ULTIMOCALCULO AS ULTIMOCALCULO,
MPRJ.VALORPROJETO AS VALORPROJETO,
MTRF.CODTRF AS ITEM,
MITMCNT.DESCRICAO AS DESCRICAO,
MTRF.CODUND AS UNIDADE,
MITMCNT.QUANTIDADE AS QUANTIDADE,
MITMCNT.VALORATUAL AS VALORUNIT,
(MITMCNT.VALORATUAL * MITMCNT.QUANTIDADE) AS VALORTOTAL, 
MTRFMED.QUANTIDADEMEDIDA AS QUANTIDADEMEDIDA,
MTRFMED.VALORMEDIDO AS VALORMEDIDO
FROM MITMCNT MITMCNT
INNER JOIN MPRJ MPRJ ON	MITMCNT.IDPRJ = MPRJ.IDPRJ
INNER JOIN MPDO MPDO ON	MITMCNT.IDCNT = MPDO.IDCNT AND MITMCNT.IDPRJ = MPDO.IDPRJ
INNER JOIN MTRF MTRF ON MITMCNT.IDTRF = MTRF.IDTRF AND MITMCNT.IDPRJ = MTRF.IDPRJ
LEFT JOIN MTRFMED MTRFMED ON MITMCNT.IDCNT = MTRFMED.IDCNT AND MITMCNT.IDPRJ = MTRFMED.IDPRJ AND MITMCNT.IDITMCNT = MTRFMED.IDITMCNT
WHERE
MTRF.ATIVA = 1
AND MPDO.VISIVELPORTAL = 1
AND MPRJ.IDPRJ =:IDPRJ
AND MITMCNT.IDCNT =:IDCNT
AND MPDO.PERIODOMED =:PERIODOMED
ORDER BY MITMCNT.IDCNT, MTRF.CODTRF
