TABELAS
MTRFMED - Medições
MITMCNT - Itens do Contratos
MRETPADRAO - Retenções Padrões de Itens de Contrato
MTRF - Tarefas
MPRJ - Projeto

SELECT 
(MPRJ.CODPRJ || ' - ' || MPRJ.DESCRICAO) AS PROJETO,
MPRJ.ULTIMOCALCULO AS ULTIMOCALCULO,
MPRJ.VALORPROJETO AS VALORPROJETO,
MTRF.IDPRJ AS IDPRJ,
MTRF.CODTRF AS ITEM,
MTRF.DESCRICAO AS DESCRICAO,
MTRF.CODUND AS UNIDADE,
MTRF.QUANTIDADE AS QUANTIDADE,
MTRF.VALORUNIT AS VALORUNIT,
MTRF.VALORTOTAL AS VALORTOTAL
FROM MTRF MTRF
INNER JOIN MPRJ MPRJ ON	MTRF.IDPRJ = MPRJ.IDPRJ
WHERE MTRF.IDPRJ =:IDPRJ
AND MTRF.ATIVA = 1


// Projeto 114





