TABELAS
MTRFMED - Medições
MITMCNT - Itens do Contratos
MRETPADRAO - Retenções Padrões de Itens de Contrato
MTRF - Tarefas
MPRJ - Projeto
MPDO - Periodo

SELECT 
(MPRJ.CODPRJ || ' - ' || MPRJ.DESCRICAO) AS PROJETO,
MPRJ.ULTIMOCALCULO AS ULTIMOCALCULO,
MPRJ.VALORPROJETO AS VALORPROJETO,
MITMCNT.IDPRJ AS IDPRJ,
MTRF.CODTRF AS ITEM,
MITMCNT.DESCRICAO AS DESCRICAO,
MTRF.CODUND AS UNIDADE,
MITMCNT.QUANTIDADE AS QUANTIDADE,
MITMCNT.VALORATUAL AS VALORUNIT,
(MITMCNT.VALORATUAL * MITMCNT.QUANTIDADE) AS VALORTOTAL, 
CONVERT(VARCHAR, MPDO.RECMODIFIEDON, 103) AS DATAMODIFICA,
MITMCNT.IDCNT AS IDCNT,
MPDO.PERIODOMED AS PERIODOMED,
MPDO.CLASSIFICACAO AS PERCLASSIFICACAO
FROM MITMCNT MITMCNT
INNER JOIN MPRJ MPRJ ON	MITMCNT.IDPRJ = MPRJ.IDPRJ
INNER JOIN MPDO MPDO ON	MITMCNT.IDCNT = MPDO.IDCNT AND MITMCNT.IDPRJ = MPDO.IDPRJ
INNER JOIN MTRF MTRF ON MITMCNT.IDTRF = MTRF.IDTRF AND MITMCNT.IDPRJ = MTRF.IDPRJ
WHERE
MTRF.ATIVA = 1
AND MPDO.VISIVELPORTAL = 1
AND CONVERT(VARCHAR, MPDO.RECMODIFIEDON, 103) = CONVERT(VARCHAR, getdate(), 103)
ORDER BY MITMCNT.IDCNT, MTRF.CODTRF


// Projeto 114




