Homologação

SELECT 
MCNTCOMPL.IDPRJ AS IDPRJ,
MCNTCOMPL.IDCNT AS IDCNT,
MCNTCOMPL.COUSUARIO AS COUSUARIO,
MCNTCOMPL.GRUSUARIO AS GRUSUARIO,
MCNTCOMPL.DIRUSUARIO AS DIRUSUARIO,
MCNTCOMPL.PRUSUARIO AS PRUSUARIO,
(SELECT D.DESCRICAO
	FROM GCONSIST D
	INNER JOIN MCNTCOMPL C ON D.CODINTERNO = C.COUSUARIO
	WHERE D.CODTABELA = '1'
	 AND C.IDPRJ = MCNTCOMPL.IDPRJ
	AND C.IDCNT = MCNTCOMPL.IDCNT) AS COORDENADOR,
(SELECT D.DESCRICAO
	FROM GCONSIST D
	INNER JOIN MCNTCOMPL C ON D.CODINTERNO = C.GRUSUARIO
	WHERE D.CODTABELA = '1'
	 AND C.IDPRJ = MCNTCOMPL.IDPRJ
	AND C.IDCNT = MCNTCOMPL.IDCNT) AS GERENTE,
(SELECT D.DESCRICAO
	FROM GCONSIST D
	INNER JOIN MCNTCOMPL C ON D.CODINTERNO = C.DIRUSUARIO
	WHERE D.CODTABELA = '1'
	 AND C.IDPRJ = MCNTCOMPL.IDPRJ
	AND C.IDCNT = MCNTCOMPL.IDCNT) AS DIRETOR,
(SELECT D.DESCRICAO
	FROM GCONSIST D
	INNER JOIN MCNTCOMPL C ON D.CODINTERNO = C.PRUSUARIO
	WHERE D.CODTABELA = '1'
	 AND C.IDPRJ = MCNTCOMPL.IDPRJ
	AND C.IDCNT = MCNTCOMPL.IDCNT) AS PRESIDENTE
FROM MCNTCOMPL MCNTCOMPL
WHERE MCNTCOMPL.IDPRJ=:IDPRJ
AND MCNTCOMPL.IDCNT=:IDCNT



Produção
SELECT 
MCNTCOMPL.IDPRJ AS IDPRJ,
MCNTCOMPL.IDCNT AS IDCNT,
MCNTCOMPL.COORD AS COUSUARIO,
MCNTCOMPL.GER AS GRUSUARIO,
MCNTCOMPL.DIR AS DIRUSUARIO,
MCNTCOMPL.PRES AS PRUSUARIO,
(SELECT D.DESCRICAO
	FROM GCONSIST D
	INNER JOIN MCNTCOMPL C ON D.CODINTERNO = C.COORD
	WHERE D.CODTABELA = '1'
	 AND C.IDPRJ = MCNTCOMPL.IDPRJ
	AND C.IDCNT = MCNTCOMPL.IDCNT) AS COORDENADOR,
(SELECT D.DESCRICAO
	FROM GCONSIST D
	INNER JOIN MCNTCOMPL C ON D.CODINTERNO = C.GER
	WHERE D.CODTABELA = '1'
	 AND C.IDPRJ = MCNTCOMPL.IDPRJ
	AND C.IDCNT = MCNTCOMPL.IDCNT) AS GERENTE,
(SELECT D.DESCRICAO
	FROM GCONSIST D
	INNER JOIN MCNTCOMPL C ON D.CODINTERNO = C.DIR
	WHERE D.CODTABELA = '1'
	 AND C.IDPRJ = MCNTCOMPL.IDPRJ
	AND C.IDCNT = MCNTCOMPL.IDCNT) AS DIRETOR,
(SELECT D.DESCRICAO
	FROM GCONSIST D
	INNER JOIN MCNTCOMPL C ON D.CODINTERNO = C.PRES
	WHERE D.CODTABELA = '1'
	 AND C.IDPRJ = MCNTCOMPL.IDPRJ
	AND C.IDCNT = MCNTCOMPL.IDCNT) AS PRESIDENTE
FROM MCNTCOMPL MCNTCOMPL
WHERE MCNTCOMPL.IDPRJ=:IDPRJ
AND MCNTCOMPL.IDCNT=:IDCNT
