TABELAS
MTRFMED - Medições
MRETPADRAO - Retenções Padrões de Itens de Contrato

MITMCNT - Itens do Contratos
MCNT - Contrato
MTRF - Tarefas
MPRJ - Projeto
MPDO - Periodo
MTRFMED - Itens Medidos
MCNTSTATUSLOG - Historico

MPDO.STATUSMEDICAO
0 - ABERTO
1 - FECHADO

// Projeto 114

// Projeto - Contrato
SELECT 
(MPRJ.CODPRJ || ' - ' || MPRJ.DESCRICAO) AS PROJETO,
MPRJ.IDPRJ AS IDPRJ,
MCNT.NUMCNT AS CONTRATO,
MCNT.IDCNT AS IDCNT,
CONVERT(VARCHAR, MPDO.RECMODIFIEDON, 103) AS DATAMODIFICA,
MCNT.CODCFO,
MPDO.PERIODOMED AS PERIODOMED,
MPDO.CLASSIFICACAO AS PERCLASSIFICACAO
FROM MCNT MCNT
INNER JOIN MPRJ MPRJ ON	MCNT.IDPRJ = MPRJ.IDPRJ 
INNER JOIN MPDO MPDO ON	MCNT.IDCNT = MPDO.IDCNT AND MCNT.IDPRJ = MPDO.IDPRJ
WHERE
MPDO.VISIVELPORTAL = 1
AND CONVERT(VARCHAR, MPDO.RECMODIFIEDON, 103) = CONVERT(VARCHAR, getdate(), 103)
ORDER BY MCNT.IDCNT





