SELECT 
MCNTCOMPL.IDPRJ AS IDPRJ,
MCNTCOMPL.IDCNT AS IDCNT,
MCNTCOMPL.USUARIO AS USUARIO,
MCNTCOMPL.DEPARTAMENTO AS DEPARTAMENTO,
MCNTCOMPL.CARGO AS CARGO,
GCONSIST.DESCRICAO AS DESCRICAO
FROM MCNTCOMPL
INNER JOIN GCONSIST GCONSIST ON	GCONSIST.CODINTERNO = MCNTCOMPL.USUARIO OR GCONSIST.CODINTERNO = MCNTCOMPL.CARGO
WHERE IDPRJ=:IDPRJ
AND IDCNT=:IDCNT
AND GCONSIST.CODTABELA = '1' OR GCONSIST.CODTABELA = '3'


192
167
