SELECT A.CHAPA 
FROM RM.PFUNC A 
WHERE CODSECAO LIKE '%5028%' AND 
A.CODSITUACAO <> 'D' AND 
A.CODFILIAL=:FILIAL --(FLUIG.031 - DEMISSIONAL / APROVADORES SESMT)

SELECT A.CHAPA 
FROM RM.PFUNC A 
WHERE ((CODSECAO LIKE '%4087%') OR (CODSECAO LIKE '%1880%')) AND 
A.CODSITUACAO <> 'D' AND 
A.CODFILIAL=:FILIAL --(FLUIG.033 - DEMISSIONAL / APROVADORES MED TRABALHO)

SELECT A.CHAPA 
FROM RM.PFUNC A 
WHERE CODSECAO LIKE '%5149%' AND 
A.CODSITUACAO <> 'D' AND 
A.CODFILIAL=:FILIAL -- (FLUIG.034 - DEMISSIONAL / APROVADORES DP PESSOAL)

SELECT A.CHAPA 
FROM RM.PFUNC A 
WHERE ((CODSECAO LIKE '%5040%') OR (CODSECAO LIKE '%1350%') OR (CODSECAO LIKE '%5025%')) AND 
A.CODSITUACAO <> 'D' AND 
A.CODFILIAL=:FILIAL -- (FLUIG.035 - DEMISSIONAL / APROVADORES TI)

SELECT A.CHAPA 
FROM RM.PFUNC A 
WHERE ((CODSECAO LIKE '%5013%') OR (CODSECAO LIKE '%1400%')) AND 
A.CODSITUACAO <> 'D' AND 
A.CODFILIAL=:FILIAL -- (FLUIG.036 - DEMISSIONAL / APROVADORES UGP)

SELECT A.CHAPA 
FROM RM.PFUNC A 
WHERE ((CODSECAO LIKE '%5015%') OR (CODSECAO LIKE '%1201%')) AND 
A.CODSITUACAO <> 'D' AND 
A.CODFILIAL=:FILIAL -- (FLUIG.037 - DEMISSIONAL / APROVADORES FINANCEIRO)

SELECT A.CHAPA 
FROM RM.PFUNC A 
WHERE CODSECAO LIKE '%4123%' AND 
A.CODSITUACAO <> 'D' AND 
A.CODFILIAL=:FILIAL -- (FLUIG.039 - DEMISSIONAL / APROVADORES HOTELARIA)
