SELECT 
B.CODCOLIGADA,
B.CODFILIAL,
B.NOMEFANTASIA,
B.CIDADE,
CONCAT(CONCAT(CONCAT(CONCAT(RUA, ', '), NUMERO), ' - '), BAIRRO) ENDERECO,
B.TELEFONE 
FROM RM.PFUNC A 
INNER JOIN RM.GFILIAL B ON B.CODCOLIGADA=A.CODCOLIGADA AND B.CODFILIAL=A.CODFILIAL
WHERE A.CODSITUACAO<>'D' AND B.CODCOLIGADA = 3 AND A.CHAPA =:CHAPA 
ORDER BY B.NOMEFANTASIA ASC
