SELECT 
  PCCUSTO.CODCOLIGADA,
  PCCUSTO.CODCCUSTO AS NROCENCUSTOCONT,
  PCCUSTO.NOME AS NOMECENTROCUSTO,
  PFUNC.CHAPA, 
  PFUNC.NOME, 
  PFUNC.CODSECAO,

FROM PCCUSTO (NOLOCK)
INNER JOIN PFUNC (NOLOCK) ON PCCUSTO.CODCOLIGADA = PFUNC.CODCOLIGADA AND PCCUSTO.CODCCUSTO = PFUNC.CODSECAO 
WHERE PCCUSTO.CODCOLIGADA = 3
AND PCCUSTO.ATIVO = 'T'
AND PCCUSTO.CODCCUSTO = :CODCCUSTO
ORDER BY PCCUSTO.NOME ASC
