SELECT 
B.CODCOLIGADA,
B.CODFILIAL,
B.NOMEFANTASIA,
REPLACE(REPLACE(REPLACE(B.CGC, '.', ''), '/', ''), '-', '') AS CNPJ,
B.CIDADE,
(B.RUA || ', N° ' || B.NUMERO || ', ' || B.COMPLEMENTO || ', ' ||  B.BAIRRO || ', ' || B.CIDADE || '-' ||  B.ESTADO || ', CEP: ' || B.CEP) ENDERECO,
B.TELEFONE,
A.CODRECEBIMENTO 
FROM RM.PFUNC A 
INNER JOIN RM.GFILIAL B ON B.CODCOLIGADA=A.CODCOLIGADA AND B.CODFILIAL=A.CODFILIAL
WHERE A.CODSITUACAO<>'D' AND B.CODCOLIGADA = 3 AND A.CHAPA =:CHAPA 
ORDER BY B.NOMEFANTASIA ASC