070005143
4 

SELECT 
  PCCUSTO.CODCOLIGADA,
  PCCUSTO.CODCCUSTO AS NROCENCUSTOCONT,
  PCCUSTO.NOME AS NOMECENTROCUSTO,
  PCCUSTO.NUMEROFILIALCONTAB,
  PFUNC.CHAPA, 
  PFUNC.NOME, 
  PFUNC.CODSECAO

FROM PCCUSTO (NOLOCK)
LEFT JOIN PFUNC (NOLOCK) ON PCCUSTO.CODCOLIGADA = PFUNC.CODCOLIGADA AND PCCUSTO.CODCCUSTO = PFUNC.CODSECAO 
WHERE PCCUSTO.CODCOLIGADA = 3
AND PCCUSTO.ATIVO = 'T'
/*AND A.SECAODESATIVADA = 0*/
AND PCCUSTO.CODCCUSTO = :CODCCUSTO
AND (PCCUSTO.NUMEROFILIALCONTAB = :FILIAL

	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '080' THEN 02
					ELSE NULL
				END)
	
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '060' THEN 03
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '070' THEN 04
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '130' THEN 09
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '180' THEN 11
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '190' THEN 12
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '170' THEN 13
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '200' THEN 14
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '220' THEN 15
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '160' THEN 16
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '082' THEN 18
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '162' THEN 19
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '163' THEN 20
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '213' THEN 20
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '164' THEN 21
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '215' THEN 22
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '216' THEN 23
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '175' THEN 25
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '083' THEN 26
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '171' THEN 27
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '178' THEN 30
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '179' THEN 31
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '181' THEN 34
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '182' THEN 37
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '183' THEN 38
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '189' THEN 43
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '185' THEN 44
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '186' THEN 45
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '169' THEN 46
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '191' THEN 49
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '192' THEN 50
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '194' THEN 50
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '195' THEN 53
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '153' THEN 54
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '154' THEN 56
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '157' THEN 57
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '196' THEN 64
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '219' THEN 68
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '158' THEN 70
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '159' THEN 71
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '217' THEN 73
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '218' THEN 75
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '230' THEN 77
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '141' THEN 78
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '229' THEN 79
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '231' THEN 80
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '144' THEN 82
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '145' THEN 83
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '147' THEN 86
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '239' THEN 87
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '148' THEN 88
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '235' THEN 91
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '240' THEN 94
					ELSE NULL
				END)
	OR :FILIAL = (CASE SUBSTR(PCCUSTO.CODCCUSTO,1,3)
					WHEN '243' THEN 98
					ELSE NULL
				END)
	)
ORDER BY PCCUSTO.NOME ASC